#!/bin/bash
set -euo pipefail

f=${1:-$(mktemp)}

file_given() {
  [[ -z ${1:-} ]]
}
finally() {
  file_given || rm $f
}
trap finally EXIT

qrencode -o $f
file_given || display -filter box -resize 300x300 $f
