#!/bin/bash

if [[ -d .git ]]; then
  cat <<EOF
pwd: $PWD
git:
  branch: $(git branch --show)
  remotes:
$(git remote -v | sed -e 's/^/    - /')
EOF
fi
if hash pyenv 2>/dev/null; then
  cat <<EOF
pyenv:
  version: $(pyenv version)
  python: $(pyenv which python)
EOF
fi
