#!/bin/bash
set -euo pipefail

input_url=$1
temp="${input_url#*://}"
domain="${temp%%/*}"
path="${temp#*/}"
IFS='/' read -r seg1 seg2 _ <<< "$path"
project="$seg1/$seg2"

url=$(gitlab -g "$domain" -o json project-pipeline list --project-id "$project" --no-get-all --per-page 1 | jq -r '.[0].web_url')
set -x
ci-pipeline-notify "$url"
