#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

domain=$1
project=$2

url=$(gitlab -g $domain -o json project-pipeline list --project-id $project --no-get-all --per-page 1 | jq -r '.[0].web_url')
set -x
ci-pipeline-notify $url
