#!/bin/bash
# shellcheck disable=SC2086
set -e

# https://github.com/felixhummel/clipboard
# Copyright Felix Hummel
# License: MIT

PREFERRED_TARGETS="UTF8_STRING image/png"

if [[ $* =~ -h|--help ]]; then
  cat<<EOF
Usage: clipboard [-h|--help]

EXAMPLES

Copy STDIN:
  echo 'Hello, world!' | clipboard

Paste to STDOUT:
  clipboard

Paste image to file:
  clipboard > foo.png
EOF
  exit 0
fi

do_output() {
  target=$1
  if [[ $target =~ image/ ]]; then
    # stdout is a tty
    if [[ -t 1 ]]; then
      # try to print sixels
      if hash img2sixel &>/dev/null; then
        # print img in terminal
        exec xclip -selection clipboard -out -target $target | img2sixel
        return
      fi
      cat <<EOF >&2
Will not print image.
Either use a terminal with sixel support and install img2sixel
or run "$0 > foo.png".
EOF
      exit 1
    fi
  fi
  exec xclip -selection clipboard -out -target $target
}

if [[ -t 0 ]]; then  # stdin is a TTY
  targets=$(xclip -selection clipboard -out -target TARGETS)
  # if there is no text, then check if it's an image
  for target in $PREFERRED_TARGETS; do
    if [[ $targets =~ $target ]]; then
      do_output $target
      exit
    fi
  done
else
  target=UTF8_STRING
  t=$(mktemp)
  cp /dev/stdin $t
  mime=$(file --brief --mime-type $t)
  if echo $mime | grep -q ^image; then
    target=$mime
  fi
  exec xclip -selection clipboard -target $target -in $t
  exit
fi
