#!/usr/bin/env python
# encoding: utf-8
from datetime import datetime
from subprocess import check_output, check_call

dt = datetime.now().strftime('%Y-%m')

latest_tag = check_output(
    f'git tag | grep ^{dt} | sort | tail -n1', shell=True, text=True
)


def get_minor(tag):
    try:
        return tag.split('.')[1]
    except IndexError:
        return None


minor = get_minor(latest_tag)
if minor is None:
    minor = 0
else:
    minor = int(minor) + 1

new_tag = f'{dt}.{minor}'

check_call(f'git tag {new_tag}', shell=True)
print(new_tag)
