#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

BAKDIR=~/bak/bash_history

cd $BAKDIR
# https://unix.stackexchange.com/a/155077/120440
if [[ -n "$(git status --untracked-files=no --porcelain)" ]]; then
  echo "repo not clean: $BAKDIR" >&2
  exit 1
fi

cp ~/.bash_history ./
git add .bash_history
git commit -m "felix-bash-history-backup"
