#!/usr/bin/env python
# encoding: utf-8
# https://docs.python.org/3/howto/curses.html

import curses
import time
import datetime


INTERVAL_SECONDS = 0.49  # second-precision, shannon


def main(stdscr):
    # hide cursor
    curses.curs_set(0)
    try:
        while True:
            dt = datetime.datetime.now()
            s = dt.strftime('%y-%m-%d %H:%M')
            stdscr.clear()
            stdscr.addstr(0, 0, s)
            stdscr.refresh()

            time.sleep(INTERVAL_SECONDS)
    except KeyboardInterrupt:
        return

if __name__ == '__main__':
    curses.wrapper(main)
