#!/bin/bash
set -euo pipefail

usage() {
  name=${0##*/}
  cat <<EOF
Usage: $name TARGET

    TARGET is an rsync target. Each volume name gets appended, e.g.
        $name example.com:/var/backups/foo
        Would result in /var/backups/foo/vol1, /var/backups/foo/vol2, ... on the box example.com.
EOF
}

[[ -z ${1:-} ]] && { usage; exit 1; }
target=${1%/}

volumes=$(felix-docker-compose-volumes-list)
for v in $volumes; do
  sudo du -sh /var/lib/docker/volumes/$v
  sudo rsync -ah /var/lib/docker/volumes/$v/ $target/$v/
done
