#!/bin/bash
set -euo pipefail

# My photos are usually 4032x2268 or
# identify -format "%w %h" 20240831_122037.jpg

MAX=${MAX:-1000}

me=$(basename $0)

if [[ $# != 2 ]]; then
  cat <<EOF
  Usage: $me INPUT OUTPUT

  Convert HD picture from phone to small picture ready for a blog.

  - resize to \$MAX (default: MAX=$MAX)
  - keep exif rotation
  - remove exif data

  Example:

    $me foo.jpg bar.jpg

  Sources:

  https://stackoverflow.com/a/7262050/241240

EOF
  exit 1
fi

input_file="$1"
output_file="$2"


convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85% -resize ${MAX}x${MAX} -auto-orient "$input_file" "$output_file"
echo "$output_file" >&2
