#!/usr/bin/env python
# encoding: utf-8
from subprocess import check_output


def repo_wc(path):
    commits = check_output("git log --since=2023-01-01 --author=felix --pretty=format:'%H' --reverse", cwd=path, shell=True, text=True).split('\n')

    def wc(commit):                                                           
        return int(check_output(f"git show --word-diff=porcelain {commit} '*.md' | rg '^[+]' | wc -w", shell=True, text=True, cwd=path))

    wcs = [wc(c) for c in commits]                                                                                                                                      
    return sum(wcs)           


if __name__ == '__main__':
    import sys
    from pathlib import Path
    paths = [Path(a) for a in sys.argv[1:]]
    result = {path: repo_wc(path) for path in paths}
    for p, c in result.items():
        print(p, c)
    print(sum(result.values()))
