#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

# https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/
new_default_sc=$1

old_default_sc=$(kubectl get storageclass -o jsonpath='{.items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")].metadata.name}')
echo "old: $old_default_sc" >&2

kubectl patch storageclass $old_default_sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass $new_default_sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
