#!/bin/bash
set -euo pipefail

OUTFILE="favicon.ico"

if [[ $# != 1 ]]; then
  cat<<EOF >&2
Usage: $0 <caption>

Will generate $OUTFILE
EOF
fi

if [[ -f $OUTFILE ]]; then
  echo "Will not overwrite $OUTFILE" >&2
  exit 1
fi

_debug() {
  # echo $@ >&2
  return
}

caption="$1"

convert -size 32x32 -fill white -background black \
  -font Noto-Mono \
  -gravity Center \
  caption:"$caption" \
  -flatten $OUTFILE
