#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "sqlglot"
# ]
# ///
import sqlglot

import sys

sql = sys.stdin.read()
print(sqlglot.transpile(sql, identify=True, pretty=True)[0])
