#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

zone_id=${1:-}

_filter() {
  if [[ -n $zone_id ]]; then
    rg $zone_id
  else
    cat
  fi
}

echo "zone_id id type name value" >&2
curl -fSsL "https://dns.hetzner.com/api/v1/records" \
  -H "Auth-API-Token: $HETZNER_DNS_TOKEN" \
  | jq -r '.records | .[] | "\(.zone_id) \(.id) \(.type) \(.name) \(.value)"' \
  | _filter \
  | sort
