#!/bin/bash
set -euo pipefail

domain=$1

get_expiry_dt() {
  openssl s_client -connect $1:443 2>/dev/null <<< "exit" \
    | rg -A4 's:CN =' \
    | rg --only-matching 'NotAfter: (.+)$' -r '$1'
}

dt="$(get_expiry_dt $domain)"
date --date="$dt" +'%F %H:%M:%S'
