#!/bin/bash
set -euo pipefail
# based on https://stackoverflow.com/a/32622147/241240

img=$1

curl -s -S "https://registry.hub.docker.com/v2/repositories/library/$img/tags/" \
  | jq -r '."results"[]["name"]' \
  | sort \
  | sed -e "s/^/$img:/"
