#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

psql "$@" <<'EOF'
SELECT
    pid,
    usename,
    application_name,
    query
FROM pg_stat_activity
WHERE pid <> pg_backend_pid()  -- Exclude your own session
ORDER BY backend_start;
EOF

echo "Kill session with" >&2
echo "SELECT pg_terminate_backend(pid);" >&2
