#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

MY_KEY=~/.ssh/id_ed25519.pub

config_file="$1"
shift
new_age_ssh_recipients=("$@")

encrypted_keys=$(rg '^(.+) = \{ age =' "$config_file" --only-matching -r'$1')

for key in $encrypted_keys; do
  value="${!key}"  # key is the name of the variable, e.g. FTP_PASSWORD. We need $FTP_PASSWORD.
  recipient_args=(--age-ssh-recipient $MY_KEY)
  for r in "${new_age_ssh_recipients[@]}"; do
    recipient_args+=(--age-ssh-recipient "$r")
  done
  echo "$value" | mise set --file "$config_file" --age-encrypt "${recipient_args[@]}" --prompt "$key"
done
