#!/bin/bash
set -euo pipefail

die() { echo "$@" 2>&1; exit 1; }

directories="$@"
for d in "$@"; do
  gitignore=$d/.gitignore

  [[ ! -d $1 ]] && die "$1 must be a directory"
  [[ -f $gitignore ]] && die "$gitignore already exists"

  cat <<'EOF' > $gitignore
*
!.gitignore
EOF

  git add $gitignore
done
