#!/bin/bash
# shellcheck disable=SC2086
#
# Usage:
#
#   cd ~/hacks/foo-bar
#   felix-pyenv-virtualenv
#
# Results in virtualenv called "foo-bar"
#
#
# Arguments:
#   felix-pyenv-virtualenv [MAJOR_VERSION] [NAME]
#
# Example:
#
#   felix-pyenv-virtualenv 3.10 test310

# get latest pyenv version; fall back to default
# This could break in any number of ways (no "rg", no "sort -V"). :>
set -euo pipefail

name=${2:-$(basename $PWD)}

major_v=${1:-3.11}
version=$(pyenv versions --bare --skip-aliases | rg "^${major_v}" | rg -v envs | sort -V | tail -n1 || echo "3.11.6")

# TODO LBYL instead of ignoring all errors
pyenv virtualenv $version $name || true
pyenv local $name

pip=$(pyenv which pip)

$pip install -q -U pip

if [[ ! -f .gitignore  ]] || rg -q '/\.python-version' .gitignore; then
  echo '.python-version' >> .gitignore
fi

# log
cat <<EOF >&2
$(pyenv version)
$(pyenv which python)
EOF
