#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

if [[ $# -lt 1 ]]; then
  cat <<EOF >&2
Usage: $0 PATTERN
See https://help.seafile.com/syncing_client/excluding_files/
EOF
  exit 1
fi

echo "$1" >> seafile-ignore.txt
