#!/bin/bash
set -euo pipefail

# it's OK to ignore "Invalid data found when processing input"
# https://github.com/acaudwell/Gource/issues/216

xvfb-run \
  felix-gource-play --output-framerate 60 --output-ppm-stream - \
  | ffmpeg \
    -hide_banner -probesize 50M -y -r 60 -f image2pipe -vcodec ppm \
    -i - \
    -vcodec libvpx -an -b:v 8M \
    gource.webm
