#!/bin/bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  cat<<EOF >&2
Usage: $0 <caption> [fg] [bg]

Will generate <caption>.png.

  Options

fg  foreground color (default: white)
bg  background color (default: black)


  Examples

felix-logo-generator hello
# color names
felix-logo-generator black-on-white black white
# css colors
felix-logo-generator pink-on-green '#ff00ff' '#00ff00'
# short css colors
felix-logo-generator pink-on-green '#f0f' '#0f0'
EOF
fi

_debug() {
  # echo $@ >&2
  return
}

caption="$1"
fg="${2:-white}"
bg="${3:-black}"
caplen=${#caption}
_debug "$caplen"

outfile="$caption.png"

s=400
# factor comes from experimentation
pointsize=$(echo "$s / $caplen * 1.5" | bc)
_debug "$pointsize"

convert -size ${s}x${s} -fill "$fg" -background "$bg" \
  -font Noto-Mono -pointsize "$pointsize" \
  -gravity Center caption:"$caption" \
  -flatten "$outfile"
