#!/bin/bash
set -euo pipefail
# https://stackoverflow.com/a/61821807/241240

dir=${1:-$PWD}
name=$(basename $dir)
target=/tmp/felix-docker-context/$name

mkdir -p /tmp/felix-docker-context
rm -rf /tmp/felix-docker-context/$name

printf 'FROM scratch\nCOPY . /' | DOCKER_BUILDKIT=1 docker build -f- -o $target $dir
echo $target >&2
