#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

commands=(
  "nmcli connection down wg0"
  "nmcli connection up wg0"
)

selection=$(printf "%s\n" "${commands[@]}" | rofi -dmenu)
$selection
