#!/bin/bash
set -euo pipefail

name=$1

target=~/.local/share/applications/chrome-$name.desktop
[[ ! -f $target ]]

user_data_dir=$HOME/.config/google-chrome/$name
[[ ! -d $user_data_dir ]]

cat <<EOF > $target
[Desktop Entry]
Version=1.0
Type=Application
Name=$name chrome
Exec=google-chrome --user-data-dir=$user_data_dir
Icon=google-chrome
Path=/tmp
Terminal=false
StartupNotify=true
EOF
