#!/bin/bash
set -euo pipefail

WIDTH=${WIDTH:-1000}

me=$(basename $0)

if [[ $# != 2 ]]; then
  cat <<EOF
  Usage: $me INPUT OUTPUT

  Convert HD picture from phone to small picture ready for a blog.

  - resize to \$WIDTH (default: WIDTH=$WIDTH)
  - remove exif data

  Example:

    $me foo.jpg bar.jpg

  Sources:

  https://stackoverflow.com/a/7262050/241240

EOF
  exit 1
fi

input_file="$1"
output_file="$2"


convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85% -resize $WIDTH "$input_file" "$output_file"
echo "$output_file" >&2
