#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

git submodule deinit -f --all
rm -rf .git/modules
SUBMODULE_PATHS=$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }')
[ -n "$SUBMODULE_PATHS" ] && echo "$SUBMODULE_PATHS" | xargs rm -rf
git submodule update --init --remote --recursive --depth 1
