#!/bin/bash
set -euo pipefail

# My photos are usually 4032x2268 or
# identify -format "%w %h" 20240831_122037.jpg

MAX=${MAX:-1000}
BAKDIR=orig

me="$(basename "$0")"

if [[ $# -lt 1 ]]; then
  cat <<EOF
  Usage: $me FILE...

  Convert HD picture from phone to small picture ready for a blog.

  - resize to \$MAX (default: MAX=$MAX)
  - keep exif rotation
  - remove exif data

  Example:

    $me foo.jpg
    # results in a resized foo.jpg and "orig/foo.jpg"

  Sources:

  https://stackoverflow.com/a/7262050/241240

EOF
  exit 1
fi

input_files=("$@")

for filename in "${input_files[@]}"; do
  bak="$BAKDIR/$filename"
  if [[ -f "$bak" ]]; then
    echo "Will not overwrite original file '$bak'" >&2
    exit 1
  fi
  mkdir -p "$(dirname "$bak")"
  mv "$filename" "$bak"
  convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85% -resize "${MAX}x${MAX}" -auto-orient "$bak" "$filename"
done
