#!/usr/bin/env python
# encoding: utf-8
import sys

try:
    word = sys.argv[1]
except IndexError:
    word = None

NATO = """
Alfa
Bravo
Charlie
Delta
Echo
Foxtrot
Golf
Hotel
India
Juliett
Kilo
Lima
Mike
November
Oscar
Papa
Quebec
Romeo
Sierra
Tango
Uniform
Victor
Whiskey
X-ray
Yankee
Zulu
"""

NATO = NATO.strip().split('\n')

CHAR2NATO = {x[0]: x for x in NATO}

if word is None:
    print('\n'.join(NATO))
else:
    for c in word:
        print(CHAR2NATO[c.upper()])
