#!/bin/bash
# shellcheck disable=SC2086
set -euo pipefail

# https://stackoverflow.com/a/78999545/241240

crt=$1
key=$2

c=$(openssl x509 -in $crt -pubkey -noout | openssl md5)
k=$(openssl ec -in $key -pubout | openssl md5)

[[ $c == "$k" ]]
