#!/bin/bash
set -euo pipefail

# Usage: paste parts of this or
# use $0 username=foo ...

eval $@  # evil :>
payload=$(echo -n "${username}:${password}" | base64 -w0)

cat <<EOF
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ${name}
  namespace: ${namespace}
stringData:
  .dockerconfigjson: '{"auths":{"${registry}":{"auth":"${payload}"}}}'
EOF
