#!/bin/bash
set -euo pipefail

usage() {
  name=${0##*/}
  cat <<EOF
Usage: $name SRC

    SRC is an rsync source containing directories , e.g.
        $name example.com:/var/backups/foo
        Would read in /var/backups/foo/vol1, /var/backups/foo/vol2, ... on the box example.com.
        It must contain all volumes defined by the current compose project.
EOF
}

[[ -z ${1:-} ]] && { usage; exit 1; }
src=${1%/}

volumes=$(felix-docker-compose-volumes-list)
for v in $volumes; do
  sudo mkdir -p /var/lib/docker/volumes/$v
  sudo rsync -ah $src/$v/ /var/lib/docker/volumes/$v/
  sudo du -sh /var/lib/docker/volumes/$v
done
