#!/bin/bash
set -euo pipefail

if [[ $# != 1 ]]; then
  cat<<EOF >&2
Usage: $0 <caption>

Will generate <caption>.png
EOF
fi

_debug() {
  # echo $@ >&2
  return
}

caption="$1"
caplen=$(echo "$caption" | wc -c)
_debug $caplen

outfile="$caption.png"

# factor comes from experimentation
pointsize=$(echo "400 / $caplen * 1.5" | bc)
_debug $pointsize

convert -size 400x400 -fill white -background black \
  -font Noto-Mono -pointsize $pointsize \
  -gravity Center caption:"$caption" \
  -flatten $outfile
