#!/bin/bash
set -euo pipefail


dir=$1
name=$(basename $dir)
target=/tmp/felix-docker-context/$name

mkdir -p /tmp/felix-docker-context
rm -rf /tmp/felix-docker-context/$name

printf 'FROM scratch\nCOPY . /' | DOCKER_BUILDKIT=1 docker build -f- -o $target $dir
echo $target >&2
