#!/bin/bash
set -euo pipefail

slug=${1:-}

wd=$PWD
title=LOG

# use ~/LOG if we are at $HOME
if [[ "$(readlink -m "$wd")" == "$HOME" ]]; then
  wd=~/LOG
  title="PERSONAL LOG"
fi

# use ./LOG if present
[[ -d ./LOG ]] && wd=$(readlink -m ./LOG)

# change working directory
cd "$wd"

# subdirectory for year, e.g. 22/
year=$(date +%y)  # e.g. 22
dir=./$year
mkdir -p "$dir"

dt=$(date +%m-%d)  # e.g. 09-31
base=$dir/$dt
if [[ -n $slug ]]; then
  base="${base}-${slug}"
fi

# given '?' as first arg, use fzf to select an existing file
if [[ ${1:-} == '?' ]]; then
  f=$(fzf)
  $EDITOR "$f"
  return
fi

# handle "09-31-something.md"
shopt -s nullglob  # doesnotexist* --> ""
# shellcheck disable=SC2206
files=($base*.md)
case ${#files[@]} in
  0)
    f=$base.md
    ;;
  1)
    # shellcheck disable=SC2086
    f=$(echo $base*.md)
    ;;
  *)
    echo 'ERROR found multiple files' >&2
    echo >&2
    # shellcheck disable=SC2011,SC2086
    ls $base*.md | xargs -L1 echo "- " >&2
    exit 1
    ;;
esac

bash-set-terminal-title "$title"
$EDITOR "$f"
