#!/bin/bash
set -euo pipefail

dir=$PWD

# use ~/LOG if we are at $HOME
[[ "$(readlink -m $dir)" == $HOME ]] && dir=~/LOG
# use ./LOG if present
[[ -d ./LOG ]] && dir=$(readlink -m ./LOG)

# subdirectory for year, e.g. LOG/22/
year=$(date +%y)  # e.g. 22
dir=$dir/$year
mkdir -p $dir

dt=$(date +%m-%d)  # e.g. 09-31
base=$dir/$dt

# given '?' as first arg, use fzf to select an existing file
if [[ ${1:-} == '?' ]]; then
  cd $dir
  f=$(fzf)
  cd -
  $EDITOR "$dir/$f"
  return
fi

# handle "09-31-something.md"
shopt -s nullglob  # doesnotexist* --> ""
files=($base*.md)
case ${#files[@]} in
  0)
    f=$base.md
    ;;
  1)
    f=$(echo $base*.md)
    ;;
  *)
    echo 'ERROR found multiple files' >&2
    echo >&2
    ls $base*.md | xargs -L1 echo "- " >&2
    exit 1
    ;;
esac

# set terminal title
echo -ne "\033]0;LOG\007"
$EDITOR $f
