#!/bin/bash
set -euo pipefail

infile="${1:-README.md}"
abs="$(readlink -m \"$infile\")"

here="$(readlink -m $(dirname $0))"

tmpfile=/tmp/$(echo "$abs" | md5sum | cut -d' ' -f1).html
pandoc --css $here/mdpreview.css "$infile" > $tmpfile
echo file://$tmpfile
