#!/usr/bin/env python
# encoding: utf-8
import logging

import click
import dbus

log = logging.getLogger(__name__)

try:
    from dbus import DBusException
except ImportError:
    from dbus.exceptions import DBusException

def iter_players(bus):
    candidates = ['org.mpris.MediaPlayer2.vlc', 'org.mpris.MediaPlayer2.spotify']
    for candidate in candidates:
        try:
            obj = bus.get_object(candidate, '/org/mpris/MediaPlayer2')
            log.info(f'got {candidate}')
            yield obj
        except DBusException as e:
            if 'ServiceUnknown' in str(e):
                continue
            else:
                raise


def get_player():
    bus = dbus.SessionBus()
    proxy = next(iter_players(bus))
    return dbus.Interface(proxy, dbus_interface='org.mpris.MediaPlayer2.Player')


@click.command()
@click.argument('what', type=click.Choice(['PlayPause', 'Previous', 'Next']))
def main(what):
    player = get_player()
    method = player.get_dbus_method(what)
    method()


if __name__ == '__main__':
    main()
