#!/bin/bash
set -euo pipefail

LOOKUP_DIRS=(
  ~
)
REPOS_CACHE=~/.cache/nasty-boii.repos
# let nasty-boii run and copy lines from $REPOS_CACHE to $EXCLUDE_FILE
EXCLUDE_FILE=~/.config/nasty-boii-excludes

argv1=${1:-}

if [[ $argv1 == '--clear-cache' ]]; then
  rm $REPOS_CACHE
fi

log() {
  if [[ $argv1 == '-v' ]]; then
    echo "$@" >&2
  fi
}

if [[ -f $EXCLUDE_FILE ]]; then
  log "Using EXCLUDE_FILE=$EXCLUDE_FILE"
  is_excluded() {
    grep -q $1 $EXCLUDE_FILE
  }
else
  is_excluded() {
    return 1
  }
fi

if [[ ! -f $REPOS_CACHE ]]; then
  log "initializing"
  for ld in ${LOOKUP_DIRS[@]}; do
    log "looking in $ld"
    find $ld -type d -name .git > $REPOS_CACHE
  done
  log "found $(wc -l $REPOS_CACHE) repos"
else
  log "Using cache $REPOS_CACHE"
  log "Wanna clear it? Run rm -r $REPOS_CACHE"
fi

nasties=0
for r in $(cat $REPOS_CACHE); do
  is_excluded $r && continue
  x=$(dirname $r)
  cd $x
  if [[ -n $(git status -s 2>/dev/null) ]]; then
    echo "$x"
    let ++nasties
  fi
done

if [[ $nasties != 0 ]]; then
  total=$(wc -l $REPOS_CACHE | cut -d' ' -f1)
  percent=$(echo "$nasties * 100 / $total" | bc)
  log "$nasties of $total ($percent%)"
  exit 1
fi
