#!/bin/bash
set -euo pipefail

open_old="$EDITOR"
# go to end of file and insert
open_new="$EDITOR  +$ +startinsert"

# open, if exists
if [[ -f $1 ]]; then
  $open_old $1
  exit $?
fi


cat <<'EOF' > $1
#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#       "click",
#       "structlog",
# ]
# ///

EOF

chmod +x $1
$open_new $1

