#!/bin/bash
set -euo pipefail

open_old="$EDITOR"
# go to end of file and insert
open_new="$EDITOR  +$ +startinsert"

# open, if exists
if [[ -f $1 ]]; then
  $open_old $1
  exit $?
fi


cat <<'EOF' > $1
#!/usr/bin/env python
# encoding: utf-8


EOF

chmod +x $1
$open_new $1

