#!/bin/bash
set -euo pipefail

[[ $EDITOR =~ vim|nvim ]]
open_old="$EDITOR"
# go to end of file and insert
open_new="$EDITOR +$ +startinsert"

# open, if exists
if [[ -f $1 ]]; then
  $open_old $1
  exit $?
fi


cat <<'EOF' > $1
#!/bin/bash
set -euo pipefail


EOF

chmod +x $1
$open_new $1

