#!/bin/bash
set -euo pipefail

[[ -f $1 ]]

basename=$(basename $1 .tex)
[[ -n $1 ]]

docker run -it --rm --user=$(id -u) -v $(pwd):/source schickling/latex pdflatex $1

rm ./"$basename.aux" ./"$basename.log"

echo evince \"$basename.pdf\"
