#!/usr/bin/env python
# encoding: utf-8

import sys
from django.utils.text import slugify

args = sys.argv[1:]
if args:
  txt = ' '.join(args)
else:
  txt = sys.stdin.read()
print(slugify(txt, allow_unicode=True))
