#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#       "django",
# ]
# ///
import sys
from django.utils.text import slugify

args = sys.argv[1:]
if args:
    txt = ' '.join(args)
else:
    txt = sys.stdin.read()
print(slugify(txt, allow_unicode=True))
